# Generated by Django 3.1.4 on 2020-12-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('FRUITS', 'Fruits'), ('MEAT', 'Meat'), ('HEALTH', 'Health'), ('PERSONAL', 'Personal'), ('ORGANIZING', 'Organizing'), ('BATTERY', 'Battery')], max_length=20)),
                ('photo', models.ImageField(upload_to='medial/product images')),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.IntegerField()),
                ('in_stock', models.BooleanField(default=True)),
            ],
        ),
    ]
