# Generated by Django 3.1.4 on 2020-12-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201224_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('meat', 'Meat'), ('health', 'Health'), ('personal', 'Personal'), ('organizing', 'Organizing'), ('battery', 'Battery')], max_length=20),
        ),
    ]
